### ISSUE TITLE
Serve servo.org over SSL

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo.org_2014-2020#1]

**Comment by SimonSapin** [comment]
This probably means moving away from GitHub Pages. (Which is fine by me, we just need to find something else or self-host.)

**Comment by SimonSapin** [comment]
Cloudflare just [started offering free SSL](https://blog.cloudflare.com/introducing-universal-ssl/). I think that could work with GitHub Pages.

CC @metajack @larsbergstrom

**Comment by edunham** [comment]
@SimonSapin we're now on cloudflare, and get end-to-end encryption by pointing servo.org at the content from https://servo.github.io/servo.org

Added advantage of cloudflare: we now control our own DNS, rather than going through Moz IT.

**Comment by SimonSapin** [comment]
:+1:

**Comment by larsbergstrom** [comment]
@edunham nice work!
