### ISSUE TITLE
HoloLens Drums demo behavior issue

### ISSUE THREAD

**Issue by Yonet** [servo/servo.org_2014-2020#106]
The demo opens up in the user's environment but also the browser window stays between the user and the virtual objects. See the video link below:

https://youtu.be/0GgMdWr0jTU

Device: HoloLens 2

**Comment by Manishearth** [comment]
As far as I understand it, this might be an OpenXR runtime bug cc @yl-msft . Hololens does not give applications the ability to simultaneously render a 2d slate and a 3d immersive session.

**Comment by jdm** [comment]
That looks like you have the slate pinned (see the button to the left of the X button that closes it). That's either expected behaviour or an OS bug, I believe.

**Comment by Manishearth** [comment]
I was under the impression that pinning should not matter here -- immersive mode is fully exclusive. This could have changed in recent builds.

**Comment by Yonet** [comment]
@jdm you are right, unpinning fixes it. It looks like the default behavior and I think it is confusing. I just downloaded servo to a re-flashed device. 
Feel free to close this issue. Thanks!
