### ISSUE TITLE
Link to Servo starters?

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo.org_2014-2020#14]
http://servo.github.io/servo-starters/

**Comment by KiChjang** [comment]
This looks like it depends on the resolution of #2.

**Comment by jdm** [comment]
We already have servo.org/starters/, which is good enough for me.
Edit: that was to clarify that this does not depend on #2.

**Comment by edunham** [comment]
starters.servo.org now redirects to https://starters.servo.org and serves the github pages site

**Comment by edunham** [comment]
@frewsxcv Where'd you want that link to be from? The overhauled front page links to starters quite prominently. Does that resolve this issue?

**Comment by frewsxcv** [comment]
LGTM
