### ISSUE TITLE
Tor access to servo.org

### ISSUE THREAD

**Issue by burdges** [servo/servo.org_2014-2020#20]
It's impossible to access servo.org from Tor browser because the site used CloudFlare as a CDN, which gives Tor users an unsolvable CAPTCHA.

I think CloudFlare has configuration options that remove the CAPTCHA problem for Tor users, but not sure the details. Apparently CloudFlare is the only CDN that creates these issues for Tor users. In particular, their competitors like Akamai do not find Tor to be an issue. It's supposedly all due to CloudFlare using an incorrect model of web abuse designed around Email detection as opposed to the web.

**Comment by larsbergstrom** [comment]
CC @edunham for opinions here.

**Comment by burdges** [comment]
I found https://support.cloudflare.com/hc/en-us/articles/203306930 mentioned at https://trac.torproject.org/projects/tor/ticket/18361

**Comment by notriddle** [comment]
[Fixed by @eduham](https://blog.servo.org/2016/04/04/twis-58/)
