### ISSUE TITLE
nightly build timestamps

### ISSUE THREAD

**Issue by aeosynth** [servo/servo.org_2014-2020#32]
can the nightly builds have an identifier somewhere (eg in the filename, or next to the download button)? i can't tell when the builds are actually updated.

**Comment by Manishearth** [comment]
Running the binary with `--version` will give you a commit hash

**Comment by aeosynth** [comment]
that entails downloading the binary

**Comment by Manishearth** [comment]
Oh, on the website, my bad 😄

**Comment by KiChjang** [comment]
servo/download.servo.org#11

**Comment by jdm** [comment]
Closing in favour of the previously linked issue.

**Comment by aeosynth** [comment]
ah, i didn't know each subdomain had its own repo; could this repo's readme state that?

**Comment by jdm** [comment]
Yes, it could!
