### ISSUE TITLE
Add the website to the HSTS preload list

### ISSUE THREAD

**Issue by ExE-Boss** [servo/servo.org_2014-2020#47]
The [HTTP Strict Transport Security (HSTS) preload list](https://hstspreload.org) is a list of websites that is used by modern major browsers to know which websites are to be loaded only over HTTPS.

[Testing the Servo website with the HSTS preload list submission form](https://hstspreload.org/?domain=servo.org) displays the following list of issues that need to be resolved before the Servo website can be added to the HSTS preload list:

---

- **Error: No HSTS header**
  Response error: No HSTS header is present on the response.

---

### See also:
- #1
- https://github.com/servo/servo.org/issues/48

**Comment by Darkspirit** [comment]
[Done](https://hstspreload.org/?domain=servo.org) with Servo in [bug 1482947](https://bugzilla.mozilla.org/show_bug.cgi?id=1482947).
