### ISSUE TITLE
Link working three.js demos from Servo homepage

### ISSUE THREAD

**Issue by Manishearth** [servo/servo.org_2014-2020#78]
https://manishearth.net/sand/demos.html has a bunch of links to three.js webxr demos tuned especially for AR (e.g. background meshes are removed).

(They're also published on https://manishearth.github.io/webxr-three/examples/* , which might be a better URL to use)

We should make these the main demo on http://servo.org/hl-home , perhaps with the babylon demos further down since they don't quite work yet

cc @jdm

**Comment by paulrouget** [comment]
Should we copy them under /hl-home/ or should we just link them to  https://manishearth.github.io/webxr-three/examples/*?

**Comment by Manishearth** [comment]
I think directly linking is fine, I plan to keep those up to date with fixes.
